.TH epylint 1 "2010-12-15" epylint
.SH NAME
.B epylint
\- Emacs and Flymake compatible Pylint

.SH DESCRIPTION
.B epylint
is a Emacs and Flymake compatible Pylint. It runs Pylint from outside the
current package to avoid import error messages. See
.B pylint
\'s manpage for information about all available options.

.SH "SEE ALSO"
.B pylint(1), pylint-gui(1)
