classDiagram
  class Component {
    name : str
  }
  class Container {
    component_dict : dict[int, Component]
    components : list[Component]
    components_set : set[Component]
    lazy_components : Generator[Component]
  }
  Component --o Container : components
  Component --o Container : component_dict
  Component --o Container : components_set
  Component --o Container : lazy_components
