classDiagram
  class Component {
    name : str
  }
  class Container {
    components : list[Component]
    component_dict : dict[Component]
    components_set : set[Component]
    lazy_components : generator[Component]
  }
  class MultiContainer {
    mixed : list[Component, Container]
  }
  Component --o Container : components
  Component --o Container : component_dict
  Component --o Container : components_set
  Component --o Container : lazy_components
  Component --o MultiContainer : mixed
  Container --o MultiContainer : mixed
