classDiagram
  class A {
    x
  }
  class B {
    x
  }
  class C {
    x
  }
  class D {
    x
  }
  class E {
    x
  }
  class P {
  }
  P --* A : x
  P --* C : x
  P --* D : x
  P --* E : x
  P --o B : x
