classDiagram
  class A {
    x : P
  }
  class B {
    x : P
  }
  class C {
    x : P
  }
  class D {
    x : P
  }
  class E {
    x : P
  }
  class P {
  }
  P --o A : x
  P --o B : x
  P --o C : x
  P --* D : x
  P --* E : x
