classDiagram
  class Dummy {
  }
  class Dummy2 {
    alternative_optional : int | None
    alternative_optional_swapped : None | int
    alternative_union_syntax : str | int
    class_attr : list[Dummy]
    optional : Optional[Dummy]
    optional_union : Optional[int | str]
    param : str
    union : Union[int, str]
  }
