# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  fail_on_warning: true
  configuration: doc/conf.py

build:
  os: ubuntu-26.04
  tools:
    python: "3.14"
  jobs:
    install:
      - python -m pip install --upgrade pip
      - python -m pip install -e . --group docs
    pre_build:
      - towncrier build --yes --date TBA
