version: '{branch}-{build}'
build: off
cache:
  - 'C:\\tmp'
environment:
  matrix:
    - PYTHON: "C:\\Python34"
      TOXENV: "py34"

    - PYTHON: "C:\\Python35"
      TOXENV: "py35"

    - PYTHON: "C:\\Python36"
      TOXENV: "py36"

init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
  - ps: mkdir C:\tmp
install:
  - 'powershell ./appveyor/install.ps1'
  - "python -m pip install tox"
  - 'python -m pip install wheel'
  - 'python -m pip --version'
  - 'python -m tox --version'

test_script:
  - 'python -m tox'

on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*
