[tox]
minversion = 4.22
envlist = formatting, py310, py311, py312, py313, py314, py315, pypy, benchmark
skip_missing_interpreters = true
isolated_build = true

[testenv:pylint]
extras = testutils, spelling
dependency_groups =
    test
    dev
commands =
    pre-commit run pylint --all-files

[testenv:formatting]
basepython = python3
extras = testutils, spelling
dependency_groups =
    test
    dev
commands =
    pre-commit run --all-files

[testenv:mypy]
basepython = python3
deps =
    pre-commit~=2.20
commands =
    pre-commit run mypy --all-files

[testenv]
setenv =
    COVERAGE_FILE = {toxinidir}/.coverage.{envname}
extras = testutils, spelling
dependency_groups =
    !pypy: test
    !pypy: dev
    pypy: test-min
commands =
    ; Run tests, ensuring all benchmark tests do not run
    pytest --benchmark-disable {toxinidir}/tests/ {posargs:}

[testenv:spelling]
extras = testutils, spelling
dependency_groups =
    test
    dev
commands =
    pytest {toxinidir}/tests/ {posargs:} -k unittest_spelling

[testenv:coverage-html]
setenv =
    COVERAGE_FILE = {toxinidir}/.coverage
dependency_groups =
    test
    dev
skip_install = true
commands =
    coverage combine
    coverage html --ignore-errors --rcfile={toxinidir}/.coveragerc

[testenv:docs]
changedir = doc/
extras =
dependency_groups = docs
commands =
    # Readthedoc launch a slightly different command see '.readthedocs.yaml'
    # sphinx-build -T -W -E --keep-going -b html -d _build/doctrees -D language=en . _build/html
    # Changes were made for performance reasons, add or remove only if you can't reproduce.
    sphinx-build -T -W -j auto --keep-going -b html -d _build/doctrees -D language=en . _build/html
    # -E: don't use a saved environment, always read all files
    # -j auto: build in parallel with N processes where possible (special value "auto" will set N to cpu-count)

[testenv:test_doc]
extras = testutils, spelling
dependency_groups =
    test
    dev
commands =
    pytest {toxinidir}/doc/test_messages_documentation.py

[testenv:benchmark]
extras = testutils, spelling
dependency_groups =
    test
    dev
deps =
    pygal
commands =
    ; Run the only the benchmark tests, grouping output and forcing .json output so we
    ; can compare benchmark runs
    pytest --exitfirst \
    --failed-first \
    --benchmark-only \
    --benchmark-save=batch_files \
    --benchmark-save-data \
    --benchmark-autosave {toxinidir}/tests \
    --benchmark-group-by="group" \
    {posargs:}
