"""Test `keyword-arg-before-vararg` in the context of positional-only parameters"""

# pylint: disable=missing-function-docstring, unused-argument


def name1(param1, /, param2=True, *args): ...  # [keyword-arg-before-vararg]
def name2(param1=True, /, param2=True, *args): ...  # [keyword-arg-before-vararg]
def name3(param1, param2=True, /, param3=True, *args): ...  # [keyword-arg-before-vararg]
def name4(param1, /, *args): ...
def name5(param1=True, /, *args): ...
def name6(param1, /, *args, param2=True): ...
def name7(param1=True, /, *args, param2=True): ...
def name8(param1, param2=True, /, *args, param3=True): ...
