classDiagram
  class Aggregation1 {
    x
  }
  class Aggregation2 {
    x
  }
  class Association {
    x
  }
  class Composition1 {
    x
  }
  class Composition2 {
    x
  }
  class P {
  }
  Association --> P : x
  P --* Composition1 : x
  P --* Composition2 : x
  P --o Aggregation1 : x
  P --o Aggregation2 : x
