name: Feature request
description: Suggest an idea for this project
labels: [enhancement, needs triage]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure that this feature wasn't already requested or already implemented in the main branch.
  - type: textarea
    id: current-problem
    attributes:
      label: Please describe the problem this feature would solve
      description: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Please describe the desired solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
    validations:
      required: false
