# Licensed under the GPL: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
# For details: https://github.com/pylint-dev/pylint/blob/main/LICENSE
# Copyright (c) https://github.com/pylint-dev/pylint/blob/main/CONTRIBUTORS.txt

from __future__ import annotations

import os
import sys

# Pylint documentation build configuration file, created by
# sphinx-quickstart on Thu Apr  4 20:31:25 2013.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.


# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use 'os.path.abspath' to make it absolute, like shown here.
sys.path.append(os.path.abspath("exts"))
sys.path.append(os.path.abspath(".."))

# pylint: disable=wrong-import-position

# pylint: enable=wrong-import-position

# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    "pylint_features",
    "pylint_extensions",
    "pylint_messages",
    "pylint_options",
    "pyreverse_configuration",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.intersphinx",
    "sphinx_reredirects",
]


# Single file redirects are handled in this file and can be done by a pylint
# contributor. We use the following extension:
# https://documatt.gitlab.io/sphinx-reredirects/usage.html
# Directory redirects are handled in ReadTheDoc admin interface and can only be done
# by pylint maintainers at the following URL:
# https://readthedocs.org/dashboard/pylint/redirects/
redirects: dict[str, str] = {
    # "<source>": "<target>"
    "additional_commands/index": "../index.html",
    "development_guide/index": "api/index.html",
    "development_guide/contribute": "../development_guide/contributor_guide/index.html",
    "development_guide/contributor_guide": "contributor_guide/index.html",
    "development_guide/profiling": "../development_guide/contributor_guide/profiling.html",
    "development_guide/tests/index": "../contributor_guide/tests/index.html",
    "development_guide/tests/install": "../contributor_guide/tests/install.html",
    "development_guide/tests/launching_test": "../contributor_guide/tests/launching_test.html",
    # There was a restructuring of the docs; keep old links working.
}
