#!/usr/bin/env python
# Licensed under the GPL: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
# For details: https://github.com/PyCQA/pylint/blob/master/COPYING

"""Script used to generate the features file before building the actual documentation."""

import os
import subprocess
import sys

import sphinx


def builder_inited(app):
    # PACKAGE/docs/exts/pylint_extensions.py --> PACKAGE/
    base_path = os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    popen = subprocess.Popen([sys.executable, "-m", "pylint", "--full-documentation"],
                             stdout=subprocess.PIPE)
    output, _ = popen.communicate()

    if not output:
        sys.exit(popen.returncode)

    features = os.path.join(base_path, 'doc', 'features.rst')
    with open(features, 'wb') as stream:
        stream.write(b"Pylint features\n")
        stream.write(b"===============\n\n")
        stream.write(b".. generated by pylint --full-documentation\n\n")
        stream.write(output)


def setup(app):
    app.connect('builder-inited', builder_inited)
    return {'version': sphinx.__display_version__}

if __name__ == "__main__":
    builder_inited(None)
