classDiagram
  class Union {
  }
  class BaseInstance {
  }
  class Instance {
  }
  class Proxy {
  }
  class CallContext {
  }
  class InferenceContext {
  }
  class ClassModel {
  }
  class InstanceModel {
  }
  class ObjectModel {
  }
  class FilterStmtsBaseNode {
  }
  class LookupMixIn {
  }
  class Statement {
  }
  class NodeNG {
  }
  class LocalsDictNodeNG {
  }
  class ClassDef {
  }
  BaseInstance --|> Proxy
  Instance --|> BaseInstance
  ClassModel --|> ObjectModel
  InstanceModel --|> ObjectModel
  FilterStmtsBaseNode --|> NodeNG
  LookupMixIn --|> NodeNG
  Statement --|> NodeNG
  LocalsDictNodeNG --|> LookupMixIn
  ClassDef --|> FilterStmtsBaseNode
  ClassDef --|> Statement
  ClassDef --|> LocalsDictNodeNG
  BaseInstance --> ObjectModel : special_attributes
  ClassDef --> NodeNG : instance_attrs
  CallContext --* InferenceContext : callcontext
  InferenceContext --* ClassModel : context
  ClassModel --* ClassDef : special_attributes
  InstanceModel --* Instance : special_attributes
  Union --o InferenceContext : boundnode
  Instance --o InferenceContext : boundnode
  InferenceContext --o InferenceContext : boundnode
