# pylint: disable=missing-docstring,too-many-branches

def f1(expr, node_cls, x, y, z):
    if isinstance(expr, node_cls) and expr.attrname == "__init__":
        ...
    elif isinstance(expr, node_cls) or expr.attrname == "__init__":
        ...
    elif not isinstance(expr, node_cls) and expr.attrname == "__init__":
        ...
    elif not isinstance(expr, node_cls) and expr.attrname != "__init__":
        ...
    elif not isinstance(expr, node_cls) or expr.attrname == "__init__":
        ...

    if x < 0 or x > 100:
        ...
    elif x > 0 or y >= 1:
        ...
    elif x < 0 or y <= 1:
        ...

    if x is not None or y is not None:
        ...
    elif not isinstance(expr, node_cls) or x is not None:
        ...

    # +1: [consider-rewriting-conditional]
    if not isinstance(expr, node_cls) or expr.attrname != "__init__":
        ...
    elif not x or y not in z:  # [consider-rewriting-conditional]
        ...
    elif not x or y is not z:  # [consider-rewriting-conditional]
        ...
    elif not (not x or not y):  # [consider-rewriting-conditional]
        ...
    elif x and (not y or not z):  # [consider-rewriting-conditional]
        ...
    elif not x or y < 0 or z <= 0:  # [consider-rewriting-conditional]
        ...
    elif not x or y > 0 or z >= 0:  # [consider-rewriting-conditional]
        ...
