# pylint: disable=missing-docstring

def f1(expr, node_cls, x, y, z):
    if isinstance(expr, node_cls) and expr.attrname == "__init__":
        ...
    elif isinstance(expr, node_cls) or expr.attrname == "__init__":
        ...
    elif not isinstance(expr, node_cls) and expr.attrname == "__init__":
        ...
    elif not isinstance(expr, node_cls) and expr.attrname != "__init__":
        ...
    elif not isinstance(expr, node_cls) or expr.attrname == "__init__":
        ...

    if not isinstance(expr, node_cls) or expr.attrname != "__init__":  # [improve-conditionals]
        ...
    elif x > 0 or y >= 1:  # [improve-conditionals]
        ...
    elif x < 0 or y <= 1:  # [improve-conditionals]
        ...
    elif not x or y not in z:  # [improve-conditionals]
        ...
    elif not (not x or not y):  # [improve-conditionals]
        ...
    elif x and (not y or not z):  # [improve-conditionals]
        ...
